"""empty message

Revision ID: 7c84b0f09dee
Revises: 3d76e9be444d
Create Date: 2023-07-31 11:51:27.337592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c84b0f09dee'
down_revision = '3d76e9be444d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.Boolean(), server_default='false', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.drop_column('sold')

    # ### end Alembic commands ###
